### PR TITLE
Upgrade Tests & Benchmarks projects to .NET 7

### PR DESCRIPTION
**Pull request by hishamco**
While .NET 5.0 is out of support it's good to upgrade

### CODE REVIEW

**Comment by hishamco** [comment]
@sebastienros can you merge this?

**Comment by hishamco** [comment]
@sebastienros can we merge this, .net 5.0 breaks every PR

**Comment by lahma** [comment]
I think NET 8 is the correct target.

**Comment by sebastienros** [comment]
Handling it in another PR already

**Comment by hishamco** [comment]
Deleting the branch :)

**Pull request closed without merging**
