### PR TITLE
Skipping unknown shortcodes

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes https://github.com/OrchardCMS/OrchardCore/issues/7715

### CODE REVIEW

**Comment by sebastienros** [comment]
@deanmarcussen opinion on the new behavior?

**Comment by deanmarcussen** [comment]
New behaviour sounds good. 

No weirdness with nesting? i.e. some found, some not found?

**Comment by sebastienros** [comment]
New tests:
[hello] -> "Hello world!"
[upper] -> ToUpperCase

```
        [InlineData("[hello][foo]", "Hello world![foo]")]
        [InlineData("[hello  ][foo]", "Hello world![foo]")]
        [InlineData("[foo][hello]", "[foo]Hello world!")]
        [InlineData("[upper][foo][/upper]", "[FOO]")]
        [InlineData("[upper] [ foo ] [/upper]", " [ FOO ] ")]
        [InlineData("[[upper] [[] foo []] [/upper]]", "[upper] [[] foo []] [/upper]")]
        [InlineData("[[[upper] [[] foo []] [/upper]]]", "[[upper] [[] foo []] [/upper]]")]
        [InlineData("[upper] [hello] [/upper]", " HELLO WORLD! ")]
        [InlineData("[foo arg1=blah] ", "[foo arg1=blah] ")]
        [InlineData("[  foo arg1=blah  ]", "[  foo arg1=blah  ]")]
        [InlineData("[  foo arg1=blah  ] [/foo]", "[  foo arg1=blah  ] [/foo]")]
        [InlineData("[/foo]", "[/foo]")]
        [InlineData(" [/ foo ] ", " [/ foo ] ")]
```

**Comment by sebastienros** [comment]
Your comment made me think and I added more tests, obviously found issues which are now fixed.

**Pull request merged**
